-- 직급 시퀀스
CREATE SEQUENCE position_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 역할 시퀀스
CREATE SEQUENCE role_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 사용자 시퀀스
CREATE SEQUENCE employee_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 사용자 역할 매핑 시퀀스
CREATE SEQUENCE user_role_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 인사 이력 시퀀스
CREATE SEQUENCE employee_history_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 부서 시퀀스
CREATE SEQUENCE department_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 연차 잔액 시퀀스
CREATE SEQUENCE annual_leave_balance_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 근무 시간 규칙 시퀀스
CREATE SEQUENCE attendance_time_policies_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 근태 판정 기준 시퀀스
CREATE SEQUENCE attendance_thresholds_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 근무지 시퀀스
CREATE SEQUENCE workplaces_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 출퇴근 기록 시퀀스
CREATE SEQUENCE attendance_logs_seq START
WITH
    1 INCREMENT BY 1 CACHE 50 NOCYCLE;

-- 근태 결과 시퀀스
CREATE SEQUENCE attendance_results_seq START
WITH
    1 INCREMENT BY 1 CACHE 50 NOCYCLE;

-- 근태 정정 이력 시퀀스
CREATE SEQUENCE attendance_correction_seq START
WITH
    1 INCREMENT BY 1 CACHE 50 NOCYCLE;

-- 일용직 근태 기록 시퀀스
CREATE SEQUENCE attendance_logs_daily_seq START
WITH
    1 INCREMENT BY 1 CACHE 50 NOCYCLE;

-- 결재문서 시퀀스
CREATE SEQUENCE approval_document_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 결재 이력 시퀀스
CREATE SEQUENCE approval_history_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 문서유형 시퀀스
CREATE SEQUENCE document_type_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 문서 스키마 정의 시퀀스
CREATE SEQUENCE document_type_schema_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 문서처리 시퀀스
CREATE SEQUENCE document_process_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 첨부매핑 시퀀스
CREATE SEQUENCE document_attach_mapping_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 첨부파일 시퀀스
CREATE SEQUENCE attachment_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 결재선 시퀀스
CREATE SEQUENCE approval_line_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 결재위임 시퀀스
CREATE SEQUENCE approval_delegate_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 휴가유형 시퀀스
CREATE SEQUENCE leave_type_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 휴가신청 시퀀스
CREATE SEQUENCE leave_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 휴가날짜 시퀀스
CREATE SEQUENCE leave_date_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 회의실 시퀀스
CREATE SEQUENCE meeting_room_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 회의실 예약 시퀀스
CREATE SEQUENCE room_reservation_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 예약 참석자 시퀀스
CREATE SEQUENCE reservation_participant_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 일정 시퀀스
CREATE SEQUENCE schedule_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 공휴일 시퀀스
CREATE SEQUENCE holidays_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 급여 내역 시퀀스
CREATE SEQUENCE payrolls_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 급여 상세 항목 시퀀스
CREATE SEQUENCE payroll_details_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 기본급 정보 시퀀스
CREATE SEQUENCE salary_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 알림 시퀀스
CREATE SEQUENCE work_notification_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 평가 기간 시퀀스
CREATE SEQUENCE evaluation_period_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 평가 문항 시퀀스
CREATE SEQUENCE evaluation_question_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 직원 평가 시퀀스
CREATE SEQUENCE employee_evaluation_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 직원 평가 답변 시퀀스
CREATE SEQUENCE evaluation_answer_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 승진 기준 시퀀스
CREATE SEQUENCE promotion_rule_seq START
WITH
    1 INCREMENT BY 1 NOCACHE NOCYCLE;