ServerRoot "/usr/local/apache2"
Listen 80
ServerName localhost

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule headers_module modules/mod_headers.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so

User daemon
Group daemon

TypesConfig conf/mime.types

ErrorLog /proc/self/fd/2
LogFormat "%h %l %u %t \"%r\" %>s %b" common
CustomLog /proc/self/fd/1 common

ProxyRequests Off
ProxyPreserveHost On

# WebSocket
RewriteEngine On
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteCond %{HTTP:Connection} upgrade [NC]
RewriteRule ^/ws/?(.*) ws://192.168.0.2:30080/ws/$1 [P,L]

ProxyPass /ws http://192.168.0.2:30080/ws
ProxyPassReverse /ws http://192.168.0.2:30080/ws

# Backend API
ProxyPass /api http://192.168.0.2:30080/api
ProxyPassReverse /api http://192.168.0.2:30080/api

# Swagger
ProxyPass /api.html http://192.168.0.2:30080/api.html
ProxyPassReverse /api.html http://192.168.0.2:30080/api.html

ProxyPass /swagger-ui http://192.168.0.2:30080/swagger-ui
ProxyPassReverse /swagger-ui http://192.168.0.2:30080/swagger-ui

ProxyPass /v3/api-docs http://192.168.0.2:30080/v3/api-docs
ProxyPassReverse /v3/api-docs http://192.168.0.2:30080/v3/api-docs

# Frontend
ProxyPass / http://192.168.0.2:30081/
ProxyPassReverse / http://192.168.0.2:30081/
