spring.application.name=backend

# Oracle DB 연결 정보
spring.datasource.url=jdbc:oracle:thin:@192.168.0.237:1522/XEPDB1
spring.datasource.username=hr24
spring.datasource.password=hr24

# JPA 설정
# none   : 테이블 자동 생성/수정 안함
# create : 실행 시 테이블 새로 생성
# update : Entity 기준으로 테이블 자동 수정
# Hibernate가 테이블을 자동 생성/수정하지 않음 (DDL 직접 관리)
spring.jpa.hibernate.ddl-auto=none
# 실행되는 SQL을 콘솔에 출력
spring.jpa.show-sql=true
# 출력되는 SQL을 보기 좋게 정렬
spring.jpa.properties.hibernate.format_sql=true
# Oracle DB에 맞는 SQL 문법 사용
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect